<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 5.0
 * @since        Class available since Release 1.0
 */

 echo $this->getChildHtml('billing');?>

<?php if(!Mage::getSingleton('checkout/session')->getQuote()->isVirtual() && intval(Mage::getStoreConfig('gomage_checkout/general/different_shipping_enabled'))): echo $this->getChildHtml('shipping'); endif;?>