<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 5.0
 * @since        Class available since Release 5.0
 */
?>
<?php 
	$helper = Mage::helper('gomage_checkout');
?>
<style type="text/css">

	/* glc title */
	.glc-title{				
		<?php
			$_color1 = Mage::getStoreConfig('gomage_checkout/skin_header/bg_color'); 
			$_color2 = Mage::getStoreConfig('gomage_checkout/skin_header/bg_color2');
		?>
		<?php if(Mage::getStoreConfig('gomage_checkout/skin_header/gradient') && $_color1 && $_color2): ?>
      background-color: <?php echo $helper->formatColor($_color1); ?>;
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(<?php echo $helper->formatColor($_color1); ?>), to(<?php echo $helper->formatColor($_color2); ?>));
      background-image: -webkit-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:    -moz-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:      -o-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:         linear-gradient(to bottom, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
		<?php elseif ($_color1): ?>
			background: <?php echo $helper->formatColor($_color1); ?>;			
		<?php endif; ?>
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_header/font_color')): ?>
			color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_radius = Mage::getStoreConfig('gomage_checkout/skin_header/border_radius')): ?>
	 		-webkit-border-radius: <?php echo $_radius ?>px <?php echo $_radius ?>px 0 0;
      -moz-border-radius: <?php echo $_radius ?>px <?php echo $_radius ?>px 0 0;
      border-radius: <?php echo $_radius ?>px <?php echo $_radius ?>px 0 0; 
		<?php endif; ?>	
	}
  
  /* glc number */
	.glc-title span{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_header/p_bg_color')):?>
			background: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_header/p_font_color')): ?>
			color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_radius = Mage::getStoreConfig('gomage_checkout/skin_header/p_radius')): ?>
	 		-webkit-border-radius: <?php echo $_radius ?>px;
      -moz-border-radius: <?php echo $_radius ?>px;
      border-radius: <?php echo $_radius ?>px; 
		<?php endif; ?>	
	} 

	/* glc col */
	.glc-col{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/bg_color')): ?>
			background-color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/border_color')): ?>
			border-color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/font_color')): ?>
			color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_radius = Mage::getStoreConfig('gomage_checkout/skin_block/border_radius')): ?>
	 		-webkit-border-radius: 0 0 <?php echo $_radius ?>px <?php echo $_radius ?>px;
      -moz-border-radius: 0 0 <?php echo $_radius ?>px <?php echo $_radius ?>px;
      border-radius: 0 0 <?php echo $_radius ?>px <?php echo $_radius ?>px; 
		<?php endif; ?>	
	}
  .glc #checkout-review-table,
  .glc #checkout-review-table td,
  .glc #checkout-review-table th{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/border_color')): ?>
			border-color: <?php echo $helper->formatColor($_color);?> !important;
		<?php endif; ?>  
    }
  .lightcheckout-discount-form,
  .discount-bottom .lightcheckout-discount-form,
  .glc #checkout-review-table-wrapper .buttons-set,
  .glc-rewards-points{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/bg_color')): ?>
			background-color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>  
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/border_color')): ?>
			border-color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/font_color')): ?>
			color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>    
    }
  .glc .data-table .odd,
  .glc .data-table .even{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/bg_color')): ?>
			background-color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>  
    }
	/* Order Review Background Color */
	.glc .data-table tfoot{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_block/or_bg_color')): ?>
			background: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
	}

	/* Buttons */
  .simple_overlay button.button span span,
  .glc button.button span span{		
		<?php
			$_color1 = Mage::getStoreConfig('gomage_checkout/skin_button/bg_color'); 
			$_color2 = Mage::getStoreConfig('gomage_checkout/skin_button/bg_color2');
		?>
		<?php if (Mage::getStoreConfig('gomage_checkout/skin_button/gradient') && $_color1 && $_color2): ?>
      background-color: <?php echo $helper->formatColor($_color1); ?>;
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(<?php echo $helper->formatColor($_color1); ?>), to(<?php echo $helper->formatColor($_color2); ?>));
      background-image: -webkit-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:    -moz-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:      -o-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:         linear-gradient(to bottom, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
		<?php elseif ($_color1): ?>
			background: <?php echo $helper->formatColor($_color1); ?>;
		<?php endif; ?>				
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_button/font_color')):?>
			color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>
		<?php if ($_radius = Mage::getStoreConfig('gomage_checkout/skin_button/radius')): ?>
	 		-webkit-border-radius: <?php echo $_radius ?>px;
      -moz-border-radius: <?php echo $_radius ?>px;
      border-radius: <?php echo $_radius ?>px; 
		<?php endif; ?>		
	}
  .simple_overlay button.button:hover span span,
  .glc button.button:hover span span{
		<?php
			$_color1 = Mage::getStoreConfig('gomage_checkout/skin_button/mo_bg_color'); 
			$_color2 = Mage::getStoreConfig('gomage_checkout/skin_button/mo_bg_color2');
		?>
		<?php if (Mage::getStoreConfig('gomage_checkout/skin_button/gradient') && $_color1 && $_color2): ?>
      background-color: <?php echo $helper->formatColor($_color1); ?>;
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(<?php echo $helper->formatColor($_color1); ?>), to(<?php echo $helper->formatColor($_color2); ?>));
      background-image: -webkit-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:    -moz-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:      -o-linear-gradient(top, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
      background-image:         linear-gradient(to bottom, <?php echo $helper->formatColor($_color1); ?>, <?php echo $helper->formatColor($_color2); ?>);
		<?php elseif ($_color1): ?>
			background: <?php echo $helper->formatColor($_color1); ?> !important;
		<?php endif; ?>
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_button/mo_font_color')):?>
			color: <?php echo $helper->formatColor($_color); ?>;
		<?php endif; ?>		
	}

	/* Pop-up Window */
	.simple_overlay{
		<?php if ($_radius = Mage::getStoreConfig('gomage_checkout/skin_popup/radius')): ?>
	 		-webkit-border-radius: <?php echo $_radius ?>px;
      -moz-border-radius: <?php echo $_radius ?>px;
      border-radius: <?php echo $_radius ?>px; 
		<?php endif; ?>	
	}
  .simple_overlay .close,
  .glc .tool-tip #payment-tool-tip-close{
		<?php if ($_color = Mage::getStoreConfig('gomage_checkout/skin_popup/close_color')):?>
			color: <?php echo $helper->formatColor($_color);?>;
		<?php endif; ?>  
  }
</style>	